"""12 predefined exploit chain patterns for chain detection."""

CHAIN_RULES = [
    {
        "name": "Cross-Origin Account Takeover",
        "requires": ["cors", "csrf"],
        "amplifiers": [],
        "chain_severity": "Critical",
        "impact": "Attacker can hijack user sessions across origins and modify account settings via CSRF.",
        "narrative": "1. Attacker exploits CORS misconfiguration on {target} to extract authentication tokens from cross-origin requests. 2. Attacker then uses CSRF vulnerability to perform unauthorized actions (password change, email update) on the victim's account. 3. Full account takeover achieved without user interaction beyond initial visit.",
    },
    {
        "name": "XSS to Full Account Takeover",
        "requires": ["xss", "csrf"],
        "amplifiers": [],
        "chain_severity": "Critical",
        "impact": "Attacker can inject malicious scripts to steal credentials and perform unauthorized account actions.",
        "narrative": "1. Attacker injects XSS payload into {target} via user input. 2. Payload executes in victim's browser, stealing session cookies/tokens. 3. Attacker uses stolen credentials combined with CSRF bypass to modify account settings and lock out legitimate user. 4. Complete account compromise.",
    },
    {
        "name": "IDOR + Missing Rate Limit = Mass Data Enumeration",
        "requires": ["idor"],
        "amplifiers": ["rate_limit"],
        "chain_severity": "High",
        "impact": "Attacker can enumerate and exfiltrate data for thousands of users without detection.",
        "narrative": "1. Attacker identifies IDOR vulnerability on {target} allowing access to user records by ID. 2. Due to missing rate limiting, attacker can rapidly iterate through ID values. 3. Attacker harvests sensitive data (PII, emails, phone numbers) for mass exfiltration. 4. Privacy breach affecting potentially all users.",
    },
    {
        "name": "SSRF to Cloud Credential Theft",
        "requires": ["ssrf"],
        "amplifiers": [],
        "chain_severity": "Critical",
        "impact": "Attacker can access cloud metadata endpoints to steal AWS/Azure credentials and compromise cloud infrastructure.",
        "narrative": "1. Attacker discovers SSRF vulnerability on {target} in URL fetching or image processing. 2. Attacker forces server to request cloud metadata endpoint (169.254.169.254). 3. Server returns temporary AWS/Azure credentials with attached IAM permissions. 4. Attacker uses credentials to access S3 buckets, databases, and other cloud resources.",
    },
    {
        "name": "Open Redirect + OAuth Token Theft",
        "requires": ["open_redirect"],
        "amplifiers": [],
        "chain_severity": "High",
        "impact": "Attacker can steal OAuth tokens by redirecting users to attacker-controlled domain after authentication.",
        "narrative": "1. Attacker crafts malicious link with open redirect on {target} pointing to attacker.com. 2. User clicks link and authenticates, but is redirected to attacker's site with OAuth token in URL fragment. 3. Attacker's site captures token via JavaScript. 4. Attacker uses token to impersonate user on integrated OAuth services.",
    },
    {
        "name": "Stored XSS Worm (No CSP)",
        "requires": ["xss"],
        "amplifiers": ["security_headers"],
        "chain_severity": "Critical",
        "impact": "Self-propagating XSS worm can compromise all users on {target} without any user action needed.",
        "narrative": "1. Attacker injects stored XSS payload into {target} in a commonly accessed area (profile, comments, etc). 2. Payload executes for every user viewing the infected content. 3. Absence of CSP allows payload to make arbitrary requests and modify page content. 4. Payload spreads itself by injecting copies into other users' profiles. 5. Mass account compromise and data theft.",
    },
    {
        "name": "SQL Injection to Full Database Breach",
        "requires": ["sqli"],
        "amplifiers": [],
        "chain_severity": "Critical",
        "impact": "Attacker gains complete database access, exfiltrating all user data, credentials, and business secrets.",
        "narrative": "1. Attacker identifies SQL injection vulnerability on {target} in search, login, or filter parameters. 2. Attacker crafts SQL query to extract database structure and user tables. 3. Attacker modifies queries to dump all sensitive data: user credentials, payment info, PII. 4. Attacker may escalate to execute system commands on database server. 5. Complete data breach and potential lateral movement to other systems.",
    },
    {
        "name": "File Upload to Remote Code Execution",
        "requires": ["file_upload"],
        "amplifiers": ["path_traversal"],
        "chain_severity": "Critical",
        "impact": "Attacker can upload malicious files and execute arbitrary code on the server, gaining full system access.",
        "narrative": "1. Attacker identifies insecure file upload on {target} accepting executable files (PHP, JSP, etc). 2. If path traversal exists, attacker can write files outside intended directory. 3. Attacker uploads web shell or backdoor to web root. 4. Attacker accesses uploaded file via HTTP, triggering code execution. 5. Full server compromise with attacker gaining shell access.",
    },
    {
        "name": "JWT Algorithm None = Full Auth Bypass",
        "requires": ["jwt"],
        "amplifiers": [],
        "chain_severity": "Critical",
        "impact": "Attacker can forge valid authentication tokens for any user, bypassing all authentication mechanisms.",
        "narrative": "1. Attacker intercepts JWT token from {target} and analyzes its structure. 2. Attacker discovers algorithm is set to 'none' or can be changed to 'none'. 3. Attacker modifies payload with different user ID, roles, or permissions. 4. Due to 'none' algorithm, no signature verification is performed. 5. Attacker gains access as any user, potentially including administrators.",
    },
    {
        "name": "SSTI to Remote Code Execution",
        "requires": ["ssti"],
        "amplifiers": [],
        "chain_severity": "Critical",
        "impact": "Attacker can execute arbitrary Python/template code on the server, achieving full system compromise.",
        "narrative": "1. Attacker identifies Server-Side Template Injection on {target} in user input reflected in templates. 2. Attacker injects template syntax (e.g., {{7*7}}) to test for vulnerability. 3. Attacker escalates to access Python builtins like __import__ to run system commands. 4. Attacker executes reverse shell or data exfiltration script. 5. Complete server compromise.",
    },
    {
        "name": "Mass Assignment + IDOR = Privilege Escalation",
        "requires": ["mass_assignment", "idor"],
        "amplifiers": [],
        "chain_severity": "High",
        "impact": "Attacker can escalate privileges by combining mass assignment to modify roles with IDOR to access other users' resources.",
        "narrative": "1. Attacker identifies mass assignment vulnerability on {target} allowing unexpected parameters (role, admin flag) in requests. 2. Attacker uses IDOR to access another user's profile via predictable ID. 3. Attacker sends mass assignment request to modify victim's role to 'admin' or 'moderator'. 4. If not properly validated server-side, privilege escalation succeeds. 5. Attacker gains administrative access.",
    },
    {
        "name": "Command Injection = Full Server Compromise",
        "requires": ["command_injection"],
        "amplifiers": [],
        "chain_severity": "Critical",
        "impact": "Attacker can execute arbitrary system commands on the server, leading to complete infrastructure compromise.",
        "narrative": "1. Attacker identifies command injection vulnerability on {target} in parameters passed to system commands. 2. Attacker uses shell metacharacters (;, |, &&, ||, `) to chain commands. 3. Attacker executes reconnaissance commands (whoami, id, ls) to understand environment. 4. Attacker establishes reverse shell or downloads and executes backdoor. 5. Full server compromise, potential lateral movement to internal network.",
    },
]
